### ISSUE TITLE
Review of D4.2.2 (1st V&V report on implementation/ code)

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/validation#152]
Please review the current deliverable D4.2.2 | 1st V&V report on implementation/ code 

The review is open until 02.04.2014.

Document under review: 

 Type   | Name                                                     | due      | pdf | source
----|----|----|---|---
  D4.2.2 | 1st V&V report on implementation/ code | Nov-2013 | [pdf](https://github.com/openETCS/validation/blob/master/Reports/D4.2/D4.2.2-VV-Implementation/D4.2.2.pdf?raw=true)  | [source](https://github.com/openETCS/validation/blob/master/Reports/D4.2/D4.2.2-VV-Implementation/D4.2.2.tex) 

Role | Partner 
---|---
Product Owner | @jensgerlach 
Review Team | @agracia @vprevosto @MERCEmentre @UweSteinkeFromSiemens @jfrsantos @MariellePetitDoche @srieger 
Key Customers WP1 | @KlausRuedigerHase  
Key Customers WP3 | @pfjauquet @BerndHekele  @BaseliyosJacob 
Key Customers WP4 VnV-plan | @HardiHungar 
Key Customers WP4 Safety Plan | @janWelte 
Key Customers WP4 Intrenal Assessment | @FrederiqueVallee @AEbt-Jagusch
Key Customers WP5 | @openETCS/demonstrator-commiter 
Key Customers WP7 | @jastram

The role of the key customers is to guarantee completeness, accuracy and validity of the contents of a document

Please contribute to the review according to the [QA- Review Process](https://github.com/openETCS/governance/blob/master/Review%20Process/OpenETCS_ReviewProcess_0.2.1.pdf?raw=true).

@openETCS/validation-committers 
@openETCS/modeling

Please mention #152 within your issue or contribute with a pull request to the document itself.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Review of D4.2.2 (1st V&V report on implementation/ code) (#152)" gesendet am 12.06.2015 17:02:19. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
