### ISSUE TITLE
Review D4.2.2 (MERCE)

### ISSUE THREAD

**Issue by MERCEmentre** [openETCS/validation#172]
Review ~~in progress~~ for D4.2.2 (issue #152).

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Review D4.2.2 (MERCE) (#172)" gesendet am 12.06.2015 16:27:22. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
