### ISSUE TITLE
Review of D4.2.2

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/validation#174]
Link to issue #152:

* Section 1
- [ ] please add a short section about the bitwalker and its role in the development process. What is the bitwalker for and at which level of development it is used. According to
  - [x] short high- level functional description
  - [ ] the V- model
  - [ ] the specification (Link to part of the TSI-CCS)

* Section 2

Table 2.4
- [x] Please give detailed argument as to how the calculation of the total cyclomatic complexity summs up to 13 in relation to the functions. The complexity seems to be too high indicating that the complexity values of single functions have been added.

- [x] To have e.g. a line- by line exemplary calculation of the complexity could enhance the result here.

- [x] Please also take a look at the conclusion of Chapter 2.7 if the calculation of the complexity changes.

* Section 3

- [ ] A boundary value analysis of the input data could be of interest here.

* Section 3.3.4

- [ ] Please list in detail which verification conditions are not yet proven.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Review of D4.2.2 (#174)" gesendet am 12.06.2015 17:02:02. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
