### ISSUE TITLE
Use means to document each issue raised inside the report

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/validation#18]
As decided at todays WP4 SCRUM meeting we need to use means to transfer the issues raised within github into a written report.

Several approaches are possible.
Below a first selection of approaches is presented.

http://developer.github.com/v3/issues/
https://github.com/josephhainline/export_github_issues_to_csv
https://gist.github.com/unbracketed/3380407
https://github.com/colmsjo/github-issues-export

**Comment by MarcBehrens** [comment]
The way of reporting has changed to:
- All verification processes should be runnable on a ragular basis
- The resutls are reported via a mailing group and extracted to issues after review.

**Comment by MarcBehrens** [comment]
first results have been uploaded to https://github.com/openETCS/modeling/tree/master/model/validation

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Use means to document each issue raised inside the report (#18)" gesendet am 12.06.2015 16:32:11. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Use means to document each issue raised inside the report (#18)" gesendet am 12.06.2015 16:31:08. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Use means to document each issue raised inside the report (#18)" gesendet am 12.06.2015 16:31:25. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
