### ISSUE TITLE
Safety Plan: Chapter 3 - Lifecycle

### ISSUE THREAD

**Issue by ghost** [openETCS/validation#194]
Described Lifecycle: 
-The stated lifecycle is ambigues. Its not clearly divided what is System and what is Software development
-It "seems" to be compliant to the SW Lifecycle (EN50128 - Figure 4), but Reference to the Standards are missing

Overall Lifecycle:
-An overall Lifecycle should be defined (System development)
-The Overall lifecycle should have an interface to the Software-Lifecycle (usually Apportionment of System Requirements)
-The overall Lifecycle should have references to the standards (EN50126/50129)

**Comment by janWelte** [comment]
Refeences have been put in place
