### ISSUE TITLE
D4.2.3 Hazard and Risk Ananlysis Methodology

### ISSUE THREAD

**Issue by MariellePetitDoche** [openETCS/validation#196]
linked to #153 

Current version of the document is a good introduction to the attendee to cover safety issue according the current state of the project.

- § 3 Why tool qualification is out of the scope of the project ? an output is plan in WP7 dealing with this subject. And tool qualification has a strong link with design and VnV chosen methods.

- § 3.2.3 : I think that goal of verification is not only to verify system safety requirements but also to verified selected methods are well applied according to some methodological requirements (links to the quality plan). for example no dead code, naming convention,... Some example of such static verifications are done in D4.2.2 part one.

- § 4.2 : The safety requirements issued from this analysis have been formally specified and proved on an Event-B model : https://github.com/openETCS/validation/blob/master/VnVUserStories/VnVUserStorySysterel/04-Results/d-EventB-VnV/EventB-Rodin-VnV.pdf

- §5 Is method or means proposed in openETCS to improve the management of documentation ?

- § 5.1 : According to EN50129, the following part is missing in the description of the structure of the safety case   : "Description of the system : precise the scope of the system covered by the safety case". This is really important to define the scope of the risk and hazard analysis.

- § 5.2 : For future iteration of document, link to concrete example of the model-based Argumentation will be useful.

- For future iteration of the document, and maybe linked with the Safety plan: Impact of scrum process and short iterations is discussed in regards of hazard and risk analysis (in §4), however how this specific process si managed in regards of documentation, verification and validation ?

Minor comments:
- §1.2 "and th safety" -> "and the safety"
- §1.5.2 "These can be assess for the software b independent measures" :  not clear
- § 1.5.3 "These depenences" -> These dependences"
- § 2 "and detail" ->  "and detailed"
- § 2 "This specifically reference..." : the phrase is not clear
- § 3  "OpenETCS tools chain" -> OpenETCS tool chain"
- § 3 "used to formalizes" -> "used to formalize"
- § 3 "focus focus" -> "focus"
- § 3 introduction is not clear and not finished
- § 3.1 "principals" -> "principles" /  "in a detail formal" -> "in a detailed formal" / "5 main distinguishable phase" ->  "5 main distinguishable phases" /  "performed iterative" -> "performed iteratively" 
- § 3.2.2 "during the during the" -> "during the"
- § 3.2.3 "The v&v plan do specify" -> "The v& v plan shall specify"
- § 4 "have to been determined" -> "have to be determined" / "the principal software" -> "the principle software"
- § 5.1 "that the can directly be used..." : not clear
- § 5.1.3 "principals" -> "principles" (several times in the document) / "the safety case clear has to show" : not clear
- § 5.2 "is address" -> "is addressed" / "safety case present" -> "safety case presents"

**Comment by janWelte** [comment]
|Reviewer|Maj/Min/Q|Comment|Answer|OK/NOK/OPEN
|--- |--- |--- |--- |---
|MPD||Current version of the document is a good introduction to the attendee to cover safety issue according the current state of the project.||Ok
|MPD||õ 3 Why tool qualification is out of the scope of the project ? an output is plan in WP7 dealing with this subject. And tool qualification has a strong link with design and VnV chosen methods.|Yes, tool qualification is not out of scope overall. I changed the text in the way that openETCS project will not provide a completely qualified tool chain, but one that may be qualified in the future.|Ok
|MPD||õ 3.2.3 : I think that goal of verification is not only to verify system safety requirements but also to verified selected methods are well applied according to some methodological requirements (links to the quality plan). for example no dead code, naming convention,... Some example of such static verifications are done in D4.2.2 part one.|It is correct. I added this point to the chapter|OK
|MPD||õ 4.2 : The safety requirements issued from this analysis have been formally specified and proved on an Event-B model : https://github.com/openETCS/validation/blob/master/VnVUserStories/VnVUserStorySysterel/04-Results/d-EventB-VnV/EventB-Rodin-VnV.pdf|has been included in the report as a short document reference|OK
|MPD||õ5 Is method or means proposed in openETCS to improve the management of documentation ?|yes, added in introduction|Ok
|MPD||"õ 5.1 : According to EN50129, the following part is missing in the description of the structure of the safety case : ""Description of the system : precise the scope of the system covered by the safety case"". This is really important to define the scope of the risk and hazard analysis."|Addressed in new paragraph version|OK
|MPD||õ 5.2 : For future iteration of document, link to concrete example of the model-based Argumentation will be useful.|to be address in concrete work based on WP 3|Open
|MPD||For future iteration of the document, and maybe linked with the Safety plan: Impact of scrum process and short iterations is discussed in regards of hazard and risk analysis (in õ4), however how this specific process si managed in regards of documentation, verification and validation ?|to be address in concrete work based on WP 3|Open
|MPD|Minor comments:|"õ1.2 ""and th safety"" -> ""and the safety"""||OK
|MPD|Minor comments:|"õ1.5.2 ""These can be assess for the software b independent measures"" : not clear"|Sentence reformulated to clearify the meaning|OK
|MPD|Minor comments:|"õ 1.5.3 ""These depenences"" -> These dependences"""||OK
|MPD|Minor comments:|"õ 2 ""and detail"" -> ""and detailed"""|Sentence has been rephrased|OK
|MPD|Minor comments:|"õ 2 ""This specifically reference..."" : the phrase is not clear"|Sentence has been rephrased|OK
|MPD|Minor comments:|"õ 3 ""OpenETCS tools chain"" -> OpenETCS tool chain"""|corrected|OK
|MPD|Minor comments:|"õ 3 ""used to formalizes"" -> ""used to formalize"""|corrected|OK
|MPD|Minor comments:|"õ 3 ""focus focus"" -> ""focus"""|corrected|OK
|MPD|Minor comments:|õ 3 introduction is not clear and not finished||ok
|MPD|Minor comments:|"õ 3.1 ""principals"" -> ""principles"" / ""in a detail formal"" -> ""in a detailed formal"" / ""5 main distinguishable phase"" -> ""5 main distinguishable phases"" / ""performed iterative"" -> ""performed iteratively"""|corrected|OK
|MPD|Minor comments:|"õ 3.2.2 ""during the during the"" -> ""during the"""|corrected|OK
|MPD|Minor comments:|"õ 3.2.3 ""The v&v plan do specify"" -> ""The v& v plan shall specify"""|corrected|OK
|MPD|Minor comments:|"õ 4 ""have to been determined"" -> ""have to be determined"" / ""the principal software"" -> ""the principle software"""|corrected|OK
|MPD|Minor comments:|"õ 5.1 ""that the can directly be used..."" : not clear"|changed sentence|OK
|MPD|Minor comments:|"õ 5.1.3 ""principals"" -> ""principles"" (several times in the document) / ""the safety case clear has to show"" : not clear"|corrected and sentence changed|OK
|MPD|Minor comments:|"õ 5.2 ""is address"" -> ""is addressed"" / ""safety case present"" -> ""safety case presents"""|corrected|OK
