### ISSUE TITLE
Calculate Train Position: Verification

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/validation#227]
The calculation of location principles, train position and train orientation is specified in subset 026, chapt. 3.6. This function is central for the train operation and part of the first goal of WP 3 as defined in https://github.com/openETCS/SRS-Analysis/issues/9. 

The determination of the train position is based upon balise groups detected while traveling and odometry information. Therefore, the locations of balise groups passed by the train and announced by linking information have to be computed by using odometry information. Then, if the locations of the balise groups are known, the current train position can be calculated related to the balise groups. 

This is, what the function block CalculateTrainPosition to be verified, does. The verification object is made up of the following parts (see https://github.com/openETCS/SRS-Analysis/issues/34 and https://github.com/openETCS/SRS-Analysis/issues/35) : 

- A SysML model defining the functions inputs and outputs https://github.com/openETCS/modeling/tree/master/model/sysml/WP3-Initial-Architecture/ManageLocationRelatedInformation/ManageTrainPosition/CalculateTrainPosition

- The calculation algorithms derived from the requirements and specified in https://github.com/openETCS/SRS-Analysis/blob/master/System%20Analysis/WorkingRepository/Group4/SUBSET_26_3-6/DetermineTrainLocationProcedures.docx

- A scenario analysis and calculation method specified in "Train Position and Locations.odt" from @JanWelvaarts 

- A library of basic location calculation functions in https://github.com/openETCS/modeling/blob/master/model/Scade/System/ObuFunctions/ManageLocationRelatedInformation/TrainPosition/BasicLocationFunctions/

- An implementation of "CalculateTrainPosition" in https://github.com/openETCS/modeling/tree/master/model/Scade/System/ObuFunctions/ManageLocationRelatedInformation/TrainPosition/CalculateTrainPosition

Although currently not all artefacts of CalculateTrainPosition are covered completely (see https://github.com/openETCS/SRS-Analysis/issues/35), WP 4 is asked for concurrent verification (see #177). 

Fyi: @BerndHekele , @JanWelvaarts, @VNuhaan, @vgontier, @janWelte , @MarcBehrens , @faustco , @MariellePetitDoche

**Comment by UweSteinkeFromSiemens** [comment]
##### Matching of the two existing calculation algorithms: 
see https://github.com/openETCS/modeling/blob/6b1ca72f3f6ec2ba77b5ad4216ed262b0eb0ce2c/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%204/CalculateTrainPosition/Calculations/MatchingTrainPositionCalculationAlgorithms.pdf

**Comment by MarcBehrens** [comment]
results can be found here https://github.com/openETCS/validation/tree/master/MinutesOfMeeting/141028_Verification_Closing_Session_Train_Positioning
