### ISSUE TITLE
Request for Commmitter rights for Abdelnasir Mohamed

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/validation#302]
Please vote for committer rights for @abdelnasirmohamed from AEbt.

@openETCS/validation-committers

**Comment by MarcBehrens** [comment]
+1

**Comment by FrancoisRevest** [comment]
+1

**Comment by HardiHungar** [comment]
+1

Regards,

Hardi

——————————————————————————
German Aerospace Center (DLR)
Institute of Transportation Systems | Lilienthalplatz 7 | 38108 Braunschweig | Germany

PD Dr. Hardi Hungar
Phone +49 531 295-3142 | Mobile +49 176 24549353 | Fax +49 531 295-3402 | Hardi.Hungar@dlr.de<mailto:Hardi.Hungar@dlr.de> www.DLR.de/dlr/en/<http://www.dlr.de/dlr/en/> Institute of Transportation Systems<http://www.dlr.de/fs/en/>
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
We would like to announce an event::
2nd Symposium Test4Rail - DLR Braunschweig, 14 – 15 October 2015
The objective of the symposium is to identify new approaches for the optimization of tests of safety-critical, software-based railway systems. The complexity of such systems in the railway sector as well as specific requirements related to safety and availability require an enormous effort for test and commissioning today. On the other hand, modern methods and procedures for system tests are available from information technology. How do those methods improve testing by reducing the effort or increasing the error detection rate? How do they need to be adapted to be used optimally in the railway sector? Answers to these and other questions related to testing will be discussed during the Test4Rail symposium. → More information<http://www.test4rail.org/>


Von: Marc Behrens [mailto:notifications@github.com]
Gesendet: Dienstag, 1. September 2015 12:46
An: openETCS/validation
Cc: Hungar, Hardi
Betreff: [validation] Request for Commmitter rights for Abdelnasir Mohamed (#302)


Please vote for committer rights for @abdelnasirmohamed<https://github.com/abdelnasirmohamed> from AEbt.

@openETCS/validation-committers<https://github.com/orgs/openETCS/teams/validation-committers>

**Comment by janWelte** [comment]
+1

**Comment by MarcBehrens** [comment]
Welcome to the team @abdelnasirmohamed

@mahlmann can you please process the rights

**Comment by mahlmann** [comment]
done
