### ISSUE TITLE
IMPEDIMENT: We need to be able to link Papyrus and TeX documents

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/validation#74]
Resulted from Issue #62 
@janWelte can give clarification on  the usecase.

**Comment by MarcBehrens** [comment]
Issue dropped and replaced by traceability within SCADE lifecycle.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] IMPEDIMENT: We need to be able to link Papyrus and TeX documents (#74)" gesendet am 12.06.2015 16:34:46. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] IMPEDIMENT: We need to be able to link Papyrus and TeX documents (#74)" gesendet am 12.06.2015 16:35:07. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
