### ISSUE TITLE
Investigate the suitability of CPN Tools for model verification 

### ISSUE THREAD

**Issue by srieger** [openETCS/validation#78]
SP: 34
[CPN Tools](http://cpntools.org/) is an open source tool suite supporting advanced modelling with coloured Petri nets and real-time aspects. CPN Tools offer graphical tools for modelling, simulation and formal verification.

CPN Tools seems to be a possible solution for model verification in general and timed verification in particular. As the timed automata tool UPPAAL is not open source it seems that CPN Tools may be a replacement. The modelling language should be strictly more powerful.

This task covers the following subitems:
- [x] Analyse CPN Tools with respect to expressive power, modelling capabilities and property language
- [x] Build a small example model from the ETCS domain
- deferred Comparison of UPPAAL and CPN Tools
- Investigation of Eclipse integration (there is already some facility) - cancelled
- deferred How can the transformation of SysML statecharts to the CPN Tools language be achieved?
- deferred How can the transformation of SysML activity diagrams to the CPN Tools language be achieved?
- [ ] Are CPN Tools suitable for test case generation and writing adaptor code for testing code to be executed on the simulator?
- deferred Using CPN visualisation capabilities to communicate verification results with non-experts.

@srieger
@janWelte 
@christianstahl

**Comment by MarcBehrens** [comment]
@Srieger any updates on the documentation?

**Comment by srieger** [comment]
Documentation is up now. The final models will follow soon.

**Comment by srieger** [comment]
Models are online as well. See referenced commit.

**Comment by janWelte** [comment]
We should have a short talk how to go on now. I would like to take time next week to have a look.
